name: Deploy Automático HostGator

on:
  push:
    branches:
      - main # Mude para 'master' se a sua branch principal tiver esse nome

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Instalar dependências e Gerar Build
        run: |
          pnpm config set ignore-patches true
          pnpm install --no-frozen-lockfile
          pnpm run build
          
      - name: Enviar arquivos para a HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/